name: Keep Render Backend Alive

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:         # Optional: for manual runs

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Send Ping to Render Backend
        run: curl https://skill-circle-backend.onrender.com/
